name = "SlideDiskArrays"
uuid = "c4a4c3dd-55a5-5e1c-9058-bcd50f97b5e9"
authors = ["Chris Damour <damourchris@pm.me>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
OpenSlide_jll = "becf559c-afb9-529d-9a2d-92566e0304eb"

[compat]
CEnum = "0.5.0"
DiskArrays = "0.4.17"
OpenSlide_jll = "3.4.1"
julia = "1.10"
